name: "Codewiz"
description: "Your coding buddy"

inputs:
  token:
    description: "Github Access Token"
    required: true
  repo:
    description: "The repo url"
    required: true
  branch:
    description: "Branch name"
    required: true
  commit:
    description: "Commit SHA"
    required: true

runs:
  using: "node20"
  main: "dist/index.mjs"
