name: "Codewiz"
description: "Your coding buddy"
inputs:
  repo:
    description: "The repo url"
    required: true
  branch:
    description: "Branch name"
    required: true
runs:
  using: "node20"
  main: "dist/index.js"
